# Generated by Django 2.1.7 on 2019-03-20 19:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('pub_date', models.DateTimeField(verbose_name='date started')),
                ('game_name', models.CharField(default=None, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(8)])),
                ('space_value', models.IntegerField(choices=[(0, 'X'), (1, 'O')], default=None)),
                ('board_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Board')),
            ],
        ),
    ]
