# Generated by Django 2.1.7 on 2019-04-04 23:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 4, 19, 51, 18, 598394), verbose_name='date started'),
        ),
    ]
