# Generated by Django 2.1.7 on 2019-03-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20190320_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='space_value',
            field=models.CharField(choices=[(0, 'X'), (1, 'O')], default=None, max_length=1),
        ),
    ]
