# Generated by Django 2.1.7 on 2019-04-05 00:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20190404_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 4, 20, 0, 7, 946374), verbose_name='date started'),
        ),
        migrations.AlterField(
            model_name='space',
            name='space_value',
            field=models.CharField(choices=[('X', 'X'), ('O', 'O'), ('-', '-')], default='-', max_length=1),
        ),
    ]
