# Generated by Django 2.1.7 on 2019-04-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20190404_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='game_name',
        ),
        migrations.RemoveField(
            model_name='board',
            name='pub_date',
        ),
        migrations.AlterField(
            model_name='space',
            name='space_value',
            field=models.CharField(choices=[('x', 'x'), ('o', 'o'), ('-', '-')], default='-', max_length=1),
        ),
    ]
