# Generated by Django 2.1.7 on 2019-03-20 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20190320_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='space_value',
            field=models.IntegerField(choices=[(0, 'X'), (1, 'O')], default=None),
        ),
    ]
